branches:
  only:
  - master
  - eap

sudo: required

language: ruby

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - bundle exec rspec spec/acceptance/000_docker_spec.rb spec/acceptance/100_integration_spec.rb
